# Generated by Django 4.2.2 on 2023-12-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apna', '0002_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
