# Generated by Django 4.2.2 on 2023-12-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('apna', '0004_remove_cust_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cust',
            new_name='stud',
        ),
        migrations.DeleteModel(
            name='fst',
        ),
    ]
