# Generated by Django 4.2.2 on 2023-12-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apna', '0005_rename_cust_stud_delete_fst'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
