# Generated by Django 4.2.2 on 2023-12-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apna', '0007_language_delete_stud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='image',
            new_name='photo',
        ),
    ]
